name: monetio-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.6
  #
  # core
  - dask
  - netcdf4
  - numpy
  - pandas
  - s3fs
  - scipy
  - xarray
  #
  # optional
  - joblib
  - lxml
  - pyhdf
  - requests
  #
  # test
  - pytest
  - pytest-xdist
  #
  - pip>=21.1
  - pip:
      - "-e ."
